Check you can import a package by loading numpy. If you want to use the standard short name np then do so.

In [1]:
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

Define the vector v as v = (1, 2), as a numpy array. Check its shape and length. Using numpy, compute the sum of all its entries.

In [15]:
v = np.array([1,2])
v.shape

(2,)

Define the matrix A as
𝐴 = (2 3;
     6 5)
as a numpy array. Check its size and shape. Using numpy compute its transpose. Using numpy compute 𝐴𝑣.

In [3]:
A = np.array([[2, 3],[6, 5]])
print(A)
print(np.linalg.inv(A))
np.dot(A,v)

[[2 3]
 [6 5]]
[[-0.625  0.375]
 [ 0.75  -0.25 ]]


array([ 8, 16])

Using the linalg package within numpy compute the eigenvalues and eigenvectors of 𝐴.

In [4]:
np.linalg.eig(A)

(array([-1.,  8.]),
 array([[-0.70710678, -0.4472136 ],
        [ 0.70710678, -0.89442719]]))

Store the eigenvalues and eigenvectors in separate variables. Using colon, or slicing, nota􀆟on, store the first eigenvector (associated with the first eigenvalue) in a separate variable.

In [5]:
eig = np.linalg.eig(A)
print(eig)

val1 = np.linalg.eig(A)[0][0]
val2 = np.linalg.eig(A)[0][1]

print(val1)
print(val2)

vec1 = eig[1][0:2, 0:1]
vec2 = eig[1][0:2, 1:]

eig1 = [val1, vec1]
eig2 = [val2, vec2]

print("Eigenvalue and Eigenvector 1")
print(eig1)
print("Eigenvalue and Eigenvector 2")
print(eig2)

(array([-1.,  8.]), array([[-0.70710678, -0.4472136 ],
       [ 0.70710678, -0.89442719]]))
-1.0
8.0
Eigenvalue and Eigenvector 1
[-1.0, array([[-0.70710678],
       [ 0.70710678]])]
Eigenvalue and Eigenvector 2
[8.0, array([[-0.4472136 ],
       [-0.89442719]])]


numpy applies operations to its arrays elementwise. Check you understand the difference by computing the square of 𝐴 and comparing to A**2.

In [6]:
print(A)
print(np.dot(A,A))
print(A**2)

[[2 3]
 [6 5]]
[[22 21]
 [42 43]]
[[ 4  9]
 [36 25]]


Create a linearly spaced grid x with spacing dx on 𝑥 ∈ [0, 1], with 50 points (see numpy.linspace).

In [7]:
x = np.linspace(0,1,50)

Create an array integrand containing sin2(𝜋𝑥) on that grid.

In [8]:
integrand = np.sin(np.pi * x)**2

Using slicing notation and numpy.sum, use the trapezoidal rule to approximate
∫1
0
d𝑥 sin2(𝜋𝑥). To do this, sum all the interior points (not the first and last point) and multiply by the grid spacing dx.
Add the first and last points multiplied by dx/2.

In [9]:
interior_points = np.sum(integrand[1:-1])
print(interior_points)
((1/49)*(interior_points))+((1/98)*(integrand[0]+integrand[49]))

24.5


0.49999999999999994